CLOUDMQTT_URL_STR = "mqtt://hajiizqi:5H5XNSIC8a7I@farmer.cloudmqtt.com:15870"
MQTT_KEEP_ALIVE = 60

COMMAND_KEY = "COMMAND"

CMD_TAKE_OFF = "TAKE_OFF"
CMD_LAND = "LAND"
CMD_LAND_IN_SAFE_PLACE = "LAND_IN_SAFE_PLACE"
CMD_MOVE_UP = "MOVE_UP"
CMD_MOVE_DOWN = "MOVE_DOWN"
CMD_MOVE_FORWARD = "MOVE_FORWARD"
CMD_MOVE_BACK = "MOVE_BACK"
CMD_MOVE_LEFT = "MOVE_LEFT"
CMD_MOVE_RIGHT = "MOVE_RIGHT"
CMD_ROTATE_RIGHT = "ROTATE_RIGHT"
CMD_ROTATE_LEFT = "ROTATE_LEFT"
KEY_DEGREES = "DEGREES"
CMD_SET_MAX_HEIGHT = "SET_MAX_HEIGHT"
CMD_SET_MIN_HEIGHT = "SET_MIN_HEIGHT"
KEY_METER = "METER"

PROCESSED_COMMAND_KEY = "PROCESSED_COMMAND"
